#!/usr/bin/env bash
# Transfer a file from our to a server
# checks for command line arguments

if [$# -lt 4]
then 
	echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi 

# assigning paramentals to variables

path_to_file=$1
ip=$2
usernam=$3
path_to_ssh_key=$4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the transfer was successful to server
if [ $? -eq 0]
then
	echo "FILE TRANSFER SUCCESSFUL"
else
	echo "File TRANSFER FAIL"
fi
