#!/usr/bin/env bash
# Debugging nginx (service (init) must say that nginx is not running)

sudo ln -sf /etc/nginx/sites-available/deflaut /etc/nginx/sites-enabled/deflaut
sudo service nginx restart
sudo pkill "nginx"
