#!/usr/bin/env bash
# Debugging nginx (service (init) must say that nginx is not running)

In -sf /etc/nginx/sites-available/deflaut /etc/nginx/sites-enabled/deflaut
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
